name: Build Android

on:

  pull_request:

    branches-ignore:

      - ''
      
  push:

    branches-ignore:

      - ''

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y meson llvm libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-${{matrix.arch}} >build-crossfile
          git clone --depth 1 --branch 23.0 https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          git apply --reject --whitespace=fix ../mesa-zink.diff || echo "git apply failed"
          meson setup "build-android" \
            --prefix=/tmp/llvm \
            --cross-file "../build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=33 \
            -Dandroid-stub=true \
            -Dllvm=enabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=swrast \
            -Dshared-glapi=false \
            -Dbuildtype=release
          ninja -C "build-android" install
          cp /tmp/llvm/lib/libOSMesa.so.8.0.0 /tmp/llvm/lib/libOSMesa_8.so
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libllvm_${{matrix.arch}}
          path: /tmp/llvm/lib/libOSMesa_8.so

